# Generated by Django 3.2.8 on 2021-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(default='store/users/user_default.png', upload_to='store/users/'),
        ),
    ]
